-- MySQL Script generated by MySQL Workbench
-- Tue Jan  5 20:06:50 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema makekit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema makekit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `makekit` DEFAULT CHARACTER SET utf8 ;
USE `makekit` ;

-- -----------------------------------------------------
-- Table `makekit`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makekit`.`admin` (
  `adminId` VARCHAR(15) NOT NULL,
  `adminPw` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`adminId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `makekit`.`userinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makekit`.`userinfo` (
  `userEmail` VARCHAR(15) NOT NULL,
  `userPw` VARCHAR(25) NOT NULL,
  `userName` VARCHAR(10) NULL DEFAULT NULL,
  `userAddress` VARCHAR(45) NULL DEFAULT NULL,
  `userAddressDetail` VARCHAR(45) NULL DEFAULT NULL,
  `userTel` VARCHAR(15) NULL DEFAULT NULL,
  `userBirth` VARCHAR(13) NULL DEFAULT NULL,
  `userInsertDate` DATE NULL DEFAULT NULL,
  `userDeleteDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`userEmail`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `makekit`.`cartinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makekit`.`cartinfo` (
  `cartNo` INT(11) NOT NULL AUTO_INCREMENT,
  `user_userId` VARCHAR(15) NOT NULL,
  `cartDate` DATETIME NULL DEFAULT NULL,
  `cartTotalPrice` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`cartNo`, `user_userId`),
  INDEX `fk_orderinfo_user2_idx` (`user_userId` ASC) VISIBLE,
  CONSTRAINT `fk_orderinfo_user20`
    FOREIGN KEY (`user_userId`)
    REFERENCES `makekit`.`userinfo` (`userEmail`))
ENGINE = InnoDB
AUTO_INCREMENT = 69
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `makekit`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makekit`.`product` (
  `ctgType` VARCHAR(25) NOT NULL,
  `prdNo` INT(11) NOT NULL AUTO_INCREMENT,
  `prdName` VARCHAR(45) NOT NULL,
  `prdPrice` VARCHAR(10) NOT NULL,
  `prdStock` VARCHAR(5) NOT NULL,
  `prdContent` TEXT NULL DEFAULT NULL,
  `prdFilename` VARCHAR(45) NULL DEFAULT NULL,
  `prdDFilename` VARCHAR(45) NULL DEFAULT NULL,
  `prdAFilename` VARCHAR(45) NULL DEFAULT NULL,
  `registerInsertDate` DATETIME NULL DEFAULT NULL,
  `registerDeleteDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`prdNo`),
  UNIQUE INDEX `prdNo_UNIQUE` (`prdNo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `makekit`.`cartdetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makekit`.`cartdetail` (
  `cartQty` INT(11) NULL DEFAULT NULL,
  `goods_prdNo` INT(11) NOT NULL,
  `user_userId` VARCHAR(15) NOT NULL,
  `DcartNo` INT(11) NOT NULL AUTO_INCREMENT,
  `cartinfo_cartNo` INT(11) NOT NULL,
  PRIMARY KEY (`DcartNo`),
  INDEX `goods_prdNo` (`goods_prdNo` ASC) VISIBLE,
  INDEX `user_userId` (`user_userId` ASC) VISIBLE,
  INDEX `fk_orderdetail_copy1_cartinfo1_idx` (`cartinfo_cartNo` ASC) VISIBLE,
  CONSTRAINT `fk_orderdetail_copy1_cartinfo1`
    FOREIGN KEY (`cartinfo_cartNo`)
    REFERENCES `makekit`.`cartinfo` (`cartNo`),
  CONSTRAINT `orderdetail_ibfk_20`
    FOREIGN KEY (`goods_prdNo`)
    REFERENCES `makekit`.`product` (`prdNo`),
  CONSTRAINT `orderdetail_ibfk_30`
    FOREIGN KEY (`user_userId`)
    REFERENCES `makekit`.`userinfo` (`userEmail`))
ENGINE = InnoDB
AUTO_INCREMENT = 199
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `makekit`.`qna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makekit`.`qna` (
  `qSeqno` INT(11) NOT NULL AUTO_INCREMENT,
  `qTitle` VARCHAR(45) NULL DEFAULT NULL,
  `qContent` TEXT NULL DEFAULT NULL,
  `qFile` VARCHAR(35) NULL DEFAULT NULL,
  `qUserDate` DATETIME NULL DEFAULT NULL,
  `user_userId` VARCHAR(15) NOT NULL,
  `qChapter` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`qSeqno`, `user_userId`),
  INDEX `fk_qna_user1_idx` (`user_userId` ASC) VISIBLE,
  CONSTRAINT `fk_qna_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `makekit`.`userinfo` (`userEmail`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `makekit`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makekit`.`comment` (
  `admin_adminId` VARCHAR(15) NOT NULL,
  `qComment` TEXT NULL DEFAULT NULL,
  `qna_qSeqno` INT(11) NOT NULL,
  PRIMARY KEY (`admin_adminId`, `qna_qSeqno`),
  INDEX `comment_ibfk_1` (`qna_qSeqno` ASC) VISIBLE,
  CONSTRAINT `comment_ibfk_1`
    FOREIGN KEY (`qna_qSeqno`)
    REFERENCES `makekit`.`qna` (`qSeqno`),
  CONSTRAINT `fk_comment_admin1`
    FOREIGN KEY (`admin_adminId`)
    REFERENCES `makekit`.`admin` (`adminId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `makekit`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makekit`.`event` (
  `eSeqno` INT(11) NOT NULL AUTO_INCREMENT,
  `eTitle` VARCHAR(45) NULL DEFAULT NULL,
  `eContent` VARCHAR(45) NULL DEFAULT NULL,
  `eFilename` VARCHAR(45) NULL DEFAULT NULL,
  `startDate` DATE NULL DEFAULT NULL,
  `endDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`eSeqno`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `makekit`.`management`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makekit`.`management` (
  `goods_prdNo` INT(11) NOT NULL,
  `admin_adminId` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`goods_prdNo`, `admin_adminId`),
  INDEX `fk_management_admin1_idx` (`admin_adminId` ASC) VISIBLE,
  CONSTRAINT `fk_management_admin1`
    FOREIGN KEY (`admin_adminId`)
    REFERENCES `makekit`.`admin` (`adminId`),
  CONSTRAINT `fk_management_goods1`
    FOREIGN KEY (`goods_prdNo`)
    REFERENCES `makekit`.`product` (`prdNo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `makekit`.`notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makekit`.`notice` (
  `nSeqno` INT(11) NOT NULL AUTO_INCREMENT,
  `nTitle` VARCHAR(45) NOT NULL,
  `nContent` TEXT NOT NULL,
  `nDate` DATE NULL DEFAULT NULL,
  `admin_adminId` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`nSeqno`, `admin_adminId`),
  UNIQUE INDEX `seqno_UNIQUE` (`nSeqno` ASC) VISIBLE,
  INDEX `fk_notice_admin_idx` (`admin_adminId` ASC) VISIBLE,
  CONSTRAINT `fk_notice_admin`
    FOREIGN KEY (`admin_adminId`)
    REFERENCES `makekit`.`admin` (`adminId`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `makekit`.`open`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makekit`.`open` (
  `admin_adminId` VARCHAR(15) NOT NULL,
  `event_eSeqno` INT(11) NOT NULL,
  PRIMARY KEY (`admin_adminId`, `event_eSeqno`),
  INDEX `fk_open_admin1_idx` (`admin_adminId` ASC) VISIBLE,
  INDEX `open_ibfk_1` (`event_eSeqno` ASC) VISIBLE,
  CONSTRAINT `fk_open_admin1`
    FOREIGN KEY (`admin_adminId`)
    REFERENCES `makekit`.`admin` (`adminId`),
  CONSTRAINT `open_ibfk_1`
    FOREIGN KEY (`event_eSeqno`)
    REFERENCES `makekit`.`event` (`eSeqno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `makekit`.`orderinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makekit`.`orderinfo` (
  `ordNo` INT(11) NOT NULL AUTO_INCREMENT,
  `user_userId` VARCHAR(15) NOT NULL,
  `ordDate` DATETIME NULL DEFAULT NULL,
  `ordReceiver` VARCHAR(15) NULL DEFAULT NULL,
  `ordRcvAddress` VARCHAR(45) NULL DEFAULT NULL,
  `ordRcvAddressDetail` VARCHAR(45) NULL DEFAULT NULL,
  `ordRcvPhone` VARCHAR(15) NULL DEFAULT NULL,
  `ordPay` VARCHAR(6) NULL DEFAULT NULL,
  `ordBank` VARCHAR(6) NULL DEFAULT NULL,
  `ordCardNo` VARCHAR(20) NULL DEFAULT NULL,
  `ordCardPw` VARCHAR(10) NULL DEFAULT NULL,
  `ordDelivery` VARCHAR(15) NULL DEFAULT '상품 준비중',
  `ordDeliveryDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`ordNo`, `user_userId`),
  INDEX `fk_orderinfo_user2_idx` (`user_userId` ASC) VISIBLE,
  CONSTRAINT `fk_orderinfo_user2`
    FOREIGN KEY (`user_userId`)
    REFERENCES `makekit`.`userinfo` (`userEmail`))
ENGINE = InnoDB
AUTO_INCREMENT = 113
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `makekit`.`orderdetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makekit`.`orderdetail` (
  `ordQty` INT(11) NULL DEFAULT NULL,
  `ordReview` TEXT NULL DEFAULT NULL,
  `ordStar` VARCHAR(3) NULL DEFAULT NULL,
  `orderinfo_ordNo` INT(11) NOT NULL,
  `goods_prdNo` INT(11) NOT NULL,
  `user_userId` VARCHAR(15) NOT NULL,
  `ordRefund` DATETIME NULL DEFAULT NULL,
  `orddeNo` INT NOT NULL AUTO_INCREMENT,
  `orderConfirm` INT(2) NULL DEFAULT NULL,
  `ordReviewImg` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`orddeNo`),
  INDEX `fk_orderdetail_orderinfo1_idx` (`orderinfo_ordNo` ASC) VISIBLE,
  INDEX `goods_prdNo` (`goods_prdNo` ASC) VISIBLE,
  INDEX `user_userId` (`user_userId` ASC) VISIBLE,
  CONSTRAINT `orderdetail_ibfk_1`
    FOREIGN KEY (`orderinfo_ordNo`)
    REFERENCES `makekit`.`orderinfo` (`ordNo`),
  CONSTRAINT `orderdetail_ibfk_2`
    FOREIGN KEY (`goods_prdNo`)
    REFERENCES `makekit`.`product` (`prdNo`),
  CONSTRAINT `orderdetail_ibfk_3`
    FOREIGN KEY (`user_userId`)
    REFERENCES `makekit`.`userinfo` (`userEmail`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `makekit`.`participate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makekit`.`participate` (
  `user_userId` VARCHAR(15) NOT NULL,
  `win` VARCHAR(45) NULL DEFAULT 'X',
  `event_eSeqno` INT(11) NOT NULL,
  PRIMARY KEY (`user_userId`, `event_eSeqno`),
  INDEX `participate_ibfk_1` (`event_eSeqno` ASC) VISIBLE,
  CONSTRAINT `fk_participate_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `makekit`.`userinfo` (`userEmail`),
  CONSTRAINT `participate_ibfk_1`
    FOREIGN KEY (`event_eSeqno`)
    REFERENCES `makekit`.`event` (`eSeqno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `makekit`.`chatting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makekit`.`chatting` (
  `userinfo_userEmail_sender` VARCHAR(15) NOT NULL,
  `userinfo_userEmail_receiver` VARCHAR(15) NOT NULL,
  `chattingContents` TEXT NULL,
  `product_prdNo` INT(11) NOT NULL,
  INDEX `fk_chatting_userinfo1_idx` (`userinfo_userEmail_sender` ASC) VISIBLE,
  INDEX `fk_chatting_userinfo2_idx` (`userinfo_userEmail_receiver` ASC) VISIBLE,
  INDEX `fk_chatting_product1_idx` (`product_prdNo` ASC) VISIBLE,
  CONSTRAINT `fk_chatting_userinfo1`
    FOREIGN KEY (`userinfo_userEmail_sender`)
    REFERENCES `makekit`.`userinfo` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chatting_userinfo2`
    FOREIGN KEY (`userinfo_userEmail_receiver`)
    REFERENCES `makekit`.`userinfo` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chatting_product1`
    FOREIGN KEY (`product_prdNo`)
    REFERENCES `makekit`.`product` (`prdNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makekit`.`register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makekit`.`register` (
  `userinfo_userEmail` VARCHAR(15) NOT NULL,
  `product_prdNo` INT(11) NOT NULL,
  INDEX `fk_register_userinfo1_idx` (`userinfo_userEmail` ASC) VISIBLE,
  PRIMARY KEY (`product_prdNo`),
  CONSTRAINT `fk_register_userinfo1`
    FOREIGN KEY (`userinfo_userEmail`)
    REFERENCES `makekit`.`userinfo` (`userEmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_register_product1`
    FOREIGN KEY (`product_prdNo`)
    REFERENCES `makekit`.`product` (`prdNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
